language: python
python:
  - "3.6"
  - "3.7-dev"
  - "nightly"
install:
  - pip install -e .[test]
script:
  - pytest --cov-report term-missing --cov=pyzu --mypy --flake8
after_success:
  - coveralls
